import useSWR from "swr";
import Head from "next/head";
import { useRouter } from "next/router";
import { Portal, Box, useDisclosure, Text, Button, Link } from "@chakra-ui/react";
import { ChakraProvider, CSSReset } from "@chakra-ui/react";
import { QueryClient, QueryClientProvider } from "react-query";
import Navbar from "../../components/navbar/NavbarAdmin.js";
import Sidebar from "../../components/sidebar/Sidebar";

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // retryDelay: 2000,
      // refetchInterval: 5000,
      refetchOnWindowFocus: false,
    },
  },
});
export default function App({ Component, pageProps, params }) {
  const router = useRouter();
  const currentRouteName = router.route;
  const formattedRouteName = currentRouteName.split("/").pop()?.toUpperCase() || "";

  return (
    <QueryClientProvider client={queryClient}>
      <ChakraProvider>
        <Head>
          <title>Rent Cars</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <CSSReset />
        <Portal>
          <Box>
            {/* if (formattedRouteName == "[id]") {
              <Navbar brandText={params.id} />
            }else{
            <Navbar brandText={formattedRouteName} />
            } */}
            <Navbar brandText={formattedRouteName} />
          </Box>
        </Portal>
        <Box mx="auto" p={{ base: "20px", md: "30px" }} minH="200vh" pt={{ base: "110px", md: "80px", xl: "120px" }} pl={{ base: "110px", md: "80px", xl: "320px" }}>
          {/* <Dashboard /> */}
          <Sidebar />
          <Component {...pageProps} />
        </Box>
      </ChakraProvider>
    </QueryClientProvider>
  );
}
